### ISSUE TITLE
Adding section code style in code convention.

### ISSUE THREAD

**Issue by bas-boop** [Team-Swamp/IceBites#23]
Ik zou graag wat nieuws aan de [code conventie](https://github.com/Team-Swamp/IceBites/wiki/Code-convention) willen toevoegen, want het wordt niet altijd gedaan in het project.
Graag zou ik het volgende willen toevoegen onderaan de convention:

------
### Styling
Code style is a personal preference. It is needed for a group project, so here is a style that we use.

Want to look at a [class with good code style](https://github.com/Team-Swamp/IceBites/blob/develop/Assets/Scripts/Framework/SceneSwitcher.cs)?

#### Bracket placement
A good usage of brackets:
```cs
namespace ExampleNamespace
{
    public class ExampleScript : MonoBehaviour
    {
        private void ExampleMethod()
        {

        }
    }
}
```
A bad usage of brackets:
```cs
namespace ExampleNamespace{
    public class ExampleScript : MonoBehaviour{
        private void ExampleMethod(){


}       }


}
```

#### If statement and loop
Around an if and loop there needs to be an empty line above and below.
```cs
float exampleFloat;

if (_exampleBoolean)
    exampleFloat = 1;

ExampleMethod(exampleFloat);
```
```cs
int listLength = _exampleList.Length;

for (int i = 0; i < listLength; i++)
{
    Debug.LogError($"Item {listLenght} is {_exampleList[listLength].name}.");
}

ExampleMethod();
```

#### Regions
A region has a line between its content.
```cs
#region Private variables

private int _targetAmount;
private ExampleComponent _system;
private ExampleStruct _currentStruct;

#endregion
```
```cs
#region Public functions

public void ExampleMethod()
{
    Debug.Log("Example")
}

#endregion
```

#### Functions
Have a line in between functions. This is how it should be done:
```cs
/// <summary>
/// Function description.
/// </summary>
/// <param name="parameter">Parameter value to pass.</param>
/// <returns>What the function return.</returns>
public int ExampleFunction(string parameter)  
{
    Return 0;
}

private void ExampleFunction()  
{
    Debug.log("I am example!");
}
```
Not like this:

```cs
/// <summary>
/// Function description.
/// </summary>
/// <param name="parameter">Parameter value to pass.</param>
/// <returns>What the function return.</returns>
public int ExampleFunction(string parameter)  
{
    Return 0;
}
private void ExampleFunction()  
{
    Debug.log("I am example!");
}
```

**Comment by DanielNijkamp** [comment]
<img src="https://media1.tenor.com/m/HEMQmYHww6MAAAAd/borat-borat-very-nice.gif" alt="drawing" width="5000000"/>

**Comment by MartijnRene** [comment]
![cats-toby-the-cat](https://github.com/Team-Swamp/IceBites/assets/70641223/998f5887-f0f4-45f2-af9a-9bd5d030be57)

**Comment by bas-boop** [comment]
Top, dan update ik de wiki met dit.

**Comment by bas-boop** [comment]
https://github.com/Team-Swamp/IceBites/wiki/Code-convention#styling
