### ISSUE TITLE
Missing sealed classes

### ISSUE THREAD

**Issue by bas-boop** [Team-Swamp/IceBites#5]
The following class are missing the `sealed` keyword.

- [PlayerMovement.cs](https://github.com/Team-Swamp/Project-VooDoo/blob/develop/Assets/Scripts/Player/Movement/PlayerMovement.cs)
- [InputParser.cs](https://github.com/Team-Swamp/Project-VooDoo/blob/develop/Assets/Scripts/Player/Input%20Parser/InputParser.cs)
- [GridList.cs](https://github.com/Team-Swamp/Project-VooDoo/blob/develop/Assets/Scripts/Framework/GridSystem/GridList.cs)

This in imported because it's in the [code convention](https://github.com/Team-Swamp/Project-VooDoo/blob/develop/Assets/Scripts/Framework/GridSystem/GridList.cs) and it's alot nicer to have.

**Comment by wsoijer** [comment]
Sealed cannot be used for [GridList.cs](https://github.com/Team-Swamp/Project-VooDoo/blob/develop/Assets/Scripts/Framework/GridSystem/GridList.cs) since it is not valid for the type.
